name = "IFR notes"
defaultTargets = ["ifrnotes"]

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "master"

[[lean_lib]]
name = "Content"   # NEW: tells Lean that modules under Content/â€¦ exist

[[lean_lib]]
name = "IFRNotes" 

[[lean_exe]]
name = "ifrnotes"
root = "Main"